veiculos_dbt:
    target: dev
    outputs:
        dev:
            type: postgres
            threads: 1  # ou mais, conforme necessário
            host: "{{ env_var('POSTGRES_HOST') }}"
            port: "{{ env_var('POSTGRES_PORT') | int }}"
            user: "{{ env_var('POSTGRES_USER') }}"
            pass: "{{ env_var('POSTGRES_PASSWORD') }}"
            dbname: "{{ env_var('POSTGRES_DB') }}"
            schema: "{{ env_var('POSTGRES_SCHEMA', 'public') }}"
